CDXA validate content
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

diff --git a/.github/workflows/validate-cdxa.yml b/.github/workflows/validate-cdxa.yml
--- a/.github/workflows/validate-cdxa.yml
+++ b/.github/workflows/validate-cdxa.yml
@@ -62,14 +62,53 @@ jobs:
         run: |
           XML_FILES=$(gh pr view "$PR_NUMBER" --repo "$REPOSITORY" --json files | jq -r '.files[] | .path' | grep "\.xml$")
           echo "$XML_FILES" | while read XML_FILE; do
+              # Validate filename
+
+              if [[ "$XML_FILE" =~ ^([0-9]+)/jdk_([0-9]+)_0_([0-9]+)_([0-9]+)_([^_]+)_([^\.]+)\.xml$ ]]; then
+                  echo "Valid CDXA file name for update version $XML_FILE"
+                  MAJOR_FOLDER=${BASH_REMATCH[1]}
+                  MAJOR_VERSION=${BASH_REMATCH[2]}
+                  UPDATE_VERSION=${BASH_REMATCH[3]}
+                  BUILD_NUM=${BASH_REMATCH[4]}
+                  PLATFORM=${BASH_REMATCH[5]}
+                  ORG=${BASH_REMATCH[6]}
+                  JDK_BUILD="jdk-$MAJOR_VERSION.0.$UPDATE_VERSION+$BUILD_NUM"
+              elif [[ "$XML_FILE" =~ ^([0-9]+)/jdk_([0-9]+)_([0-9]+)_([^_]+)_([^\.]+)\.xml$ ]]; then
+                  echo "Valid CDXA file name for new version $XML_FILE"
+                  MAJOR_FOLDER=${BASH_REMATCH[1]}
+                  MAJOR_VERSION=${BASH_REMATCH[2]}
+                  UPDATE_VERSION="0"
+                  BUILD_NUM=${BASH_REMATCH[3]}
+                  PLATFORM=${BASH_REMATCH[4]}
+                  ORG=${BASH_REMATCH[5]}
+                  JDK_BUILD="jdk-$MAJOR_VERSION+$BUILD_NUM"
+              else
+                  echo "$XML_FILE file name is not of the correct format:"
+                  echo "    N/jdk_M_0_U_B_(Platform)_(Your Organisation).xml"
+                  echo " or N/jdk_M_B_(Platform)_(Your Organisation).xml"
+                  exit 1
+              fi
+
+              # Print bom content
               xpath -q -e '/bom' "$XML_FILE"
+
               # Ensure 1 VERIFIED_REPRODUCIBLE_BUILD
-              [ $(xpath -q -e 'count(/bom/declarations/claims/claim/predicate[text()="VERIFIED_REPRODUCIBLE_BUILD"])' "$XML_FILE") -eq 1 ]
-              # Get "target"
+              if ! [ $(xpath -q -e 'count(/bom/declarations/claims/claim/predicate[text()="VERIFIED_REPRODUCIBLE_BUILD"])' "$XML_FILE") -eq 1 ]; then
+                  echo "ERROR: $XML_FILE CDXA document does not contain a /bom/declarations/claims/claim/predicate with value VERIFIED_REPRODUCIBLE_BUILD"
+                  exit 1
+              fi
+
+              # Verify claim target with bom-ref exists
               TARGET_BOM_REF=$(xpath -q -e '/bom/declarations/claims/claim/predicate[text()="VERIFIED_REPRODUCIBLE_BUILD"]/../target/text()' "$XML_FILE")
-              # Verify target with bom-ref exists
-              if ! [ $(xpath -q -e 'count(/bom/declarations/targets/components/component[@bom-ref='"$TARGET_BOM_REF"'])' "$XML_FILE") -eq 2 ]; then
+              if ! [ $(xpath -q -e 'count(/bom/declarations/targets/components/component[@bom-ref='"$TARGET_BOM_REF"'])' "$XML_FILE") -eq 1 ]; then
                   echo "ERROR: $XML_FILE CDXA document does not contain a /bom/declarations/targets/components/component with 'bom-ref' == $TARGET_BOM_REF"
+                  exit 1
+              fi
+
+              # Verify Component.name of format: Temurin <JDK_BUILD> <PLATFORM>
+              COMPONENT_NAME=$(xpath -q -e '/bom/declarations/targets/components/component[@bom-ref="'$TARGET_BOM_REF'"]/name/text()' "$XML_FILE")
+              if [[ ! "$COMPONENT_NAME" =~ ^Temurin\ $JDK_BUILD\ $PLATFORM ]]; then
+                  echo "ERROR: $XML_FILE CDXA document /bom/declarations/targets/components/component/name is not the correct format: Temurin <JDK_BUILD> <PLATFORM>"
                   exit 1
               fi
           done
